### ISSUE TITLE
American flag needs mirrored on Shuttle Body right side

### ISSUE THREAD

**Issue by jacobohpea** [phyx-be/STS#1]
Just put together my 001 kit and noticed the flag was facing the wrong direction on that side
It's also incorrect in the photo in the readme for the repo
🇺🇸
The stars box needs to be towards the text on the right side (wrong in 001) and away from the text (correct in 001) on the left side.

**Comment by Brubacker** [comment]
Hi Jacob, 
From my research the flag should be facing "downwind" on airplanes (see airforce one and space shuttles) 
The flag looks mirrored, but the idea behind it is that there would be a virtual flagpole on the cockpit, meaning the flags "wave" to the back.
https://airandspace.si.edu/stories/editorial/heres-why-us-flag-sometimes-appears-backwards 
This article specifically shows the Space Shuttles as an example.
https://medium.com/@stefankatz/why-national-flags-appear-backwards-on-planes-ac0ae2db0d2a
The article from Medium shows that other countries do this as well. (Australia, Signapore, Italy, ... )
