### ISSUE TITLE
LED type

### ISSUE THREAD

**Issue by Sokoloft** [phyx-be/STS#2]
Hi!

Do you have a data sheet for the specific candle LED's used in this kit? I bought one off adafruit last year or so and I use it with older CR2032's I pull out of computers, keyfobs etc. However stock of those is dwindling!  I do have a bunch of old 9v batteries kicking around that have anywhere from 5-7v. Would like to rig up a couple dupont connectors, just unsure what resistor I would want.

Thanks. Great little kits btw. Love the discovery one I have.

**Comment by Brubacker** [comment]
Thanks for the compliment!
Sadly there is no datasheet available for this part, the manufacturer states 3.0~4.5V and 20mA (but they don't differentiate between blue, green, red, orange or white versions...)
So to be safe I've used a 3.0V LDO on my mini Airport to be able to power them from USB.
https://lectronz.com/products/fs-plate-00
The LDO I selected is te XC6206P302MR which you van get from LCSC : C347375, C479054 or C296234

I also made a smaller version of this to power 1 plane with 2 AAA batteries or USB : 
![image](https://github.com/user-attachments/assets/f0870ddb-5d00-4d7f-ba27-7a57517b3a90)
I'll release those files soon on github.

**Comment by Sokoloft** [comment]
ooo nice, that power board seems great!

I'm looking into LDO's now and the `LM1117-3.3` has a 4 pin sot variant. Might be able to tweak that board to accept both IC's in case a user wants to provide a bigger voltage. From what I see the `XC6206P302MR` can only take a maximum voltage of 6.5v. 

Thanks!

**Comment by Sokoloft** [comment]
Turns out I have some esp32 cams I'm not using that has one of those `LM117-3.3` on it. Took it off, used a 10uF ceramic input and 100uF electrolytic on the output. The picture is rough but its working! 


![IMG_20241113_221530602](https://github.com/user-attachments/assets/083bca0d-9444-4b3c-982d-0831dc644624)

**Comment by Brubacker** [comment]
Perfect solution!
